apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres
          image: postgres:15

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: appdb

            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD

          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
            
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d

      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: postgres-pvc
        
        - name: init-script
          configMap:
            name: postgres-init